version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/hanaTax-Frontend
    overwrite: yes
permissions:
  - object: /home/ubuntu/hanaTax-Frontend
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: /home/ubuntu/hanaTax-Frontend/deploy.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/hanaTax-Frontend/start.sh
      timeout: 60
      runas: ubuntu
